# Generated by Django 5.1.7 on 2025-03-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('conclusao', models.CharField(choices=[('Concluído', 'Concluído'), ('Não concluído', 'Não concluído')], default='Não concluído', max_length=13)),
            ],
        ),
    ]
