# Generated by Django 5.2.1 on 2025-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTask', models.CharField()),
                ('description', models.TextField()),
                ('department', models.CharField()),
                ('priority', models.CharField(choices=[('Low', 'Low Priority'), ('High', 'High Prioriry'), ('Medium', 'Medium Priority')])),
                ('createdDate', models.DateField()),
                ('status', models.CharField(choices=[('Todo', 'To-Do'), ('Done', 'Done'), ('Doing', 'Doing')], default='To-Do')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUser', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
