# Generated by Django 5.1.7 on 2025-03-28 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_JWT', '0002_userabs_telefone_alter_userabs_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userabs',
            name='cargo',
        ),
        migrations.AddField(
            model_name='userabs',
            name='animais',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userabs',
            name='biografia',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userabs',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userabs',
            name='escolaridade',
            field=models.CharField(choices=[('nal', 'NÃO ALFABEITZADO'), ('al', 'ALFABEITZADO'), ('ef', 'Ensino Fundamental'), ('em', 'Ensino Médio'), ('s', 'Superior'), ('m', 'Mestrado'), ('d', 'Doutorado')], default='nal', max_length=3),
        ),
        migrations.AddField(
            model_name='userabs',
            name='idade',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
