# Generated by Django 5.1.7 on 2025-03-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_JWT', '0003_remove_userabs_cargo_userabs_animais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userabs',
            name='animais',
            field=models.IntegerField(default=0),
        ),
    ]
