# Generated by Django 5.1.7 on 2025-03-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_JWT', '0004_alter_userabs_animais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userabs',
            name='endereco',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userabs',
            name='telefone',
            field=models.PositiveIntegerField(),
        ),
    ]
