# Generated by Django 5.1.7 on 2025-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_JWT', '0006_alter_userabs_idade_alter_userabs_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userabs',
            name='telefone2',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
